filepath: './data/pbsym_example_image.jpg'
gsd: 0.3
sensor:
  name: 'L32511x'
  # focal length (m)
  f: 4
  # telescope diameter (m)
  D: 0.273
  # detector pitch (m)
  p: 0.000008
  # Optical system transmission, red  band first (m)
  wavelength_input: [0.50, 0.66]
  # Relative linear telescope obscuration
  eta: 0.4
  # integration time (s) - this is a maximum, the actual integration time will be
  # determined by the well fill percentage
  intTime: 0.03
  # rms read noise (rms electrons)
  readNoise: 25.0
  # maximum ADC level (electrons)
  maxN: 96000.0
  # bit depth
  bitDepth: 11.9
  # maximum allowable well fill
  maxWellFill: 0.6
  # drift (radians/s)
  drift: 0.0001
  # detector quantum efficiency as a function of wavelength (microns)
  # for a generic high quality back-illuminated silicon array
  qewavelengths: [0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1]
  qe: [0.05, 0.6, 0.75, 0.85, 0.85, 0.75, 0.5, 0.2, 0]

scenario:
  name: 'niceday'
  # sensor altitude
  altitude: 4000
  # range to target
  groundRange: 0
  # weather model
  ihaze: 1
